M48
; DRILL file {KiCad 9.0.4} date 2026-01-11T11:57:00-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-11T11:57:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X67.0Y-35.0
X67.0Y-122.0
X213.0Y-35.0
X213.0Y-122.0
T2
X151.1Y-89.8
X166.34Y-39.0
X199.36Y-91.07
M30
